const { user, password } = require("../schemas/auth.schema");

const Users = {
    amol: {
        name: { first: "Amol", last: "Mathur" },
        email: "amol@blueflurry.io",
        phone1: "9971699388",
        address: {
            street: "1877/90",
            pincode: "110035",
        },
        dob: "1998-09-09",
        imageUrl: "https://dummyimage.com/400x400/DC3545",
    },
    siddhant: {
        name: { first: "Siddhant", last: "Jain" },
        email: "siddhant@blueflurry.io",
        phone1: "9711469568",
        address: {
            street: "1877/90",
            pincode: "110035",
        },
        dob: "1998-09-09",
        imageUrl: "https://dummyimage.com/400x400/007BFF",
    },
    muskaan: {
        name: { first: "Muskaan", last: "Jain" },
        email: "muskaan@blueflurry.io",
        phone1: "9873521057",
        address: {
            street: "1877/90",
            pincode: "110035",
        },
        dob: "1999-07-24",
        imageUrl: "https://dummyimage.com/400x400/DC3545",
    },
    employee: {
        name: { first: "Jaro", middle: "Connect", last: "Employee" },
        email: "employee@jaroconnect.com",
        phone1: "9199111100",
        address: {
            street: "1877/90",
            pincode: "110035",
        },
        password: "Employee@jaro@123!",
        dob: "1999-07-24",
    },
    manager: {
        name: { first: "Jaro", middle: "Connect", last: "Manager" },
        email: "manager@jaroconnect.com",
        phone1: "9299111100",
        address: {
            street: "1877/90",
            pincode: "110035",
        },
        password: "Manager@jaro@123!",
        dob: "1999-07-24",
    },
    admin: {
        name: { first: "Jaro", middle: "Connect", last: "Admin" },
        email: "admin@jaroconnect.com",
        phone1: "9399111100",
        address: {
            street: "1877/90",
            pincode: "110035",
        },
        password: "Admin@jaro@123!",
        dob: "1999-07-24",
    },
    john: {
        name: { first: "John", last: "Doe" },
        email: "john.doe@example.com",
        phone1: "9876543210",
        address: { street: "123 Main St", pincode: "110035" },
        dob: "1990-01-01",
        imageUrl: "https://dummyimage.com/400x400/FF5733",
    },
    jane: {
        name: { first: "Jane", last: "Doe" },
        email: "jane.doe@example.com",
        phone1: "9876012345",
        address: { street: "456 Elm St", pincode: "110035" },
        dob: "1992-02-02",
        imageUrl: "https://dummyimage.com/400x400/33FF57",
    },
    alice: {
        name: { first: "Alice", last: "Smith" },
        email: "alice.smith@example.com",
        phone1: "9876123456",
        address: { street: "789 Oak St", pincode: "110035" },
        dob: "1994-03-03",
        imageUrl: "https://dummyimage.com/400x400/3357FF",
    },
    bob: {
        name: { first: "Bob", last: "Johnson" },
        email: "bob.johnson@example.com",
        phone1: "9876234567",
        address: { street: "101 Pine St", pincode: "110035" },
        dob: "1996-04-04",
        imageUrl: "https://dummyimage.com/400x400/FF33A1",
    },
    charlie: {
        name: { first: "Charlie", last: "Brown" },
        email: "charlie.brown@example.com",
        phone1: "9876345678",
        address: { street: "202 Maple St", pincode: "110035" },
        dob: "1998-05-05",
        imageUrl: "https://dummyimage.com/400x400/A133FF",
    },
    david: {
        name: { first: "David", last: "Wilson" },
        email: "david.wilson@example.com",
        phone1: "9876456789",
        address: { street: "303 Birch St", pincode: "110035" },
        dob: "2000-06-06",
        imageUrl: "https://dummyimage.com/400x400/33FFA1",
    },
    emma: {
        name: { first: "Emma", last: "Davis" },
        email: "emma.davis@example.com",
        phone1: "9876567890",
        address: { street: "404 Cedar St", pincode: "110035" },
        dob: "2002-07-07",
        imageUrl: "https://dummyimage.com/400x400/FF5733",
    },
    frank: {
        name: { first: "Frank", last: "Miller" },
        email: "frank.miller@example.com",
        phone1: "9876678901",
        address: { street: "505 Walnut St", pincode: "110035" },
        dob: "2004-08-08",
        imageUrl: "https://dummyimage.com/400x400/33FF57",
    },
    grace: {
        name: { first: "Grace", last: "Martinez" },
        email: "grace.martinez@example.com",
        phone1: "9876789012",
        address: { street: "606 Chestnut St", pincode: "110035" },
        dob: "2006-09-09",
        imageUrl: "https://dummyimage.com/400x400/3357FF",
    },
    henry: {
        name: { first: "Henry", last: "Garcia" },
        email: "henry.garcia@example.com",
        phone1: "9876890123",
        address: { street: "707 Spruce St", pincode: "110035" },
        dob: "2008-10-10",
        imageUrl: "https://dummyimage.com/400x400/FF33A1",
    },
    isabella: {
        name: { first: "Isabella", last: "Martinez" },
        email: "isabella.martinez@example.com",
        phone1: "9876901234",
        address: { street: "808 Redwood St", pincode: "110035" },
        dob: "2010-11-11",
        imageUrl: "https://dummyimage.com/400x400/A133FF",
    },
    jack: {
        name: { first: "Jack", last: "Hernandez" },
        email: "jack.hernandez@example.com",
        phone1: "9877012345",
        address: { street: "909 Cypress St", pincode: "110035" },
        dob: "2012-12-12",
        imageUrl: "https://dummyimage.com/400x400/33FFA1",
    },
};

const Companies = {
    blueFlurry: {
        address: {
            street: "428/7",
            city: "Anand Parbat",
            state: "Delhi",
            country: "India",
            pincode: "110005",
        },
        data: {
            name: "Blue Flurry",
            imageUrl: "https://i.ibb.co/zW54BnHM/logo-icon-square.png",
        },
    },
    jaro: {
        address: {
            street: "11th Floor, Vikas Centre",
            city: "Mumbai",
            state: "Maharashtra",
            country: "India",
            pincode: "400074",
        },
        data: {
            name: "Jaro Education",
            imageUrl: "https://jaro-website.s3.ap-south-1.amazonaws.com/2022/03/cropped-Logo_Royal_BLue-with-red-dot-192x192.png",
        },
    },
};

const Upsells = [
    {
        type: 0,
        title: "Resume Builder",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/DC3545",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 0,
        title: "Interview Prep",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/007BFF",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
];

const Universities = [
    {
        type: 1,
        title: "Indian Institute of Technology Bombay",
        description: "Mumbai, Maharashtra",
        imageUrl: "https://dummyimage.com/400x400/FF5733",
        link: "https://www.iitb.ac.in",
    },
    {
        type: 1,
        title: "University of Delhi",
        description: "North Delhi, Delhi",
        imageUrl: "https://dummyimage.com/400x400/33FF57",
        link: "http://www.du.ac.in",
    },
    {
        type: 1,
        title: "Indian Institute of Science",
        description: "Bangalore, Karnataka",
        imageUrl: "https://dummyimage.com/400x400/3357FF",
        link: "https://www.iisc.ac.in",
    },
    {
        type: 1,
        title: "Jawaharlal Nehru University",
        description: "New Delhi, Delhi",
        imageUrl: "https://dummyimage.com/400x400/FF33A1",
        link: "https://www.jnu.ac.in",
    },
    {
        type: 1,
        title: "Banaras Hindu University",
        description: "Varanasi, Uttar Pradesh",
        imageUrl: "https://dummyimage.com/400x400/A133FF",
        link: "https://www.bhu.ac.in",
    },
    {
        type: 1,
        title: "University of Calcutta",
        description: "Kolkata, West Bengal",
        imageUrl: "https://dummyimage.com/400x400/33FFA1",
        link: "https://www.caluniv.ac.in",
    },
    {
        type: 1,
        title: "University of Mumbai",
        description: "Mumbai, Maharashtra",
        imageUrl: "https://dummyimage.com/400x400/FF5733",
        link: "http://mu.ac.in",
    },
    {
        type: 1,
        title: "Amity University",
        description: "Noida, Uttar Pradesh",
        imageUrl: "https://dummyimage.com/400x400/33FF57",
        link: "https://www.amity.edu",
    },
    {
        type: 1,
        title: "Anna University",
        description: "Chennai, Tamil Nadu",
        imageUrl: "https://dummyimage.com/400x400/3357FF",
        link: "https://www.annauniv.edu",
    },
    {
        type: 1,
        title: "University of Hyderabad",
        description: "Hyderabad, Telangana",
        imageUrl: "https://dummyimage.com/400x400/FF33A1",
        link: "https://www.uohyd.ac.in",
    },
];

const HomeCarousels = [
    {
        type: 2,
        title: "Home Carousel",
        description: "",
        imageUrl: "https://dummyimage.com/500x300",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 2,
        title: "Home Carousel",
        description: "",
        imageUrl: "https://dummyimage.com/500x300",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 2,
        title: "Home Carousel",
        description: "",
        imageUrl: "https://dummyimage.com/500x300",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 2,
        title: "Home Carousel",
        description: "",
        imageUrl: "https://dummyimage.com/500x300",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 2,
        title: "Home Carousel",
        description: "",
        imageUrl: "https://dummyimage.com/500x300",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
];

const Categories = [
    {
        type: 3,
        title: "Software Development",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/FF5733",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Data Science",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/33FF57",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Digital Marketing",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/3357FF",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Graphic Design",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/FF33A1",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Cyber Security",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/A133FF",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Project Management",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/33FFA1",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Business Analysis",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/FF5733",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Machine Learning",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/33FF57",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Artificial Intelligence",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/3357FF",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Cloud Computing",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/FF33A1",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Blockchain",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/A133FF",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Internet of Things",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/33FFA1",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "DevOps",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/FF5733",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Mobile App Development",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/33FF57",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Web Development",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/3357FF",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "UI/UX Design",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/FF33A1",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Software Testing",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/A133FF",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "IT Support",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/33FFA1",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Network Administration",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/FF5733",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
    {
        type: 3,
        title: "Database Administration",
        description: "",
        imageUrl: "https://dummyimage.com/400x400/33FF57",
        link: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
    },
];

const Courses = Categories.flatMap((category, index) => [
    {
        status: 0,
        title: `${category.title} Webinar 1`,
        description: `Learn the basics of ${category.title}.`,
        imageUrl: `https://jaro-website.s3.ap-south-1.amazonaws.com/2024/08/Management-Consulting.jpg`,
        courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
        inviteUrl: "https://www.zoom.us/signin",
        startDate: "2025-05-10T15:00:00.000+00:00",
        endDate: "2025-06-10T15:00:00.000+00:00",
        duration: Math.floor(Math.random() * 31) + 1,
        category: category.title,
        enrolled: 0,
    },
    {
        status: 0,
        title: `${category.title} Webinar 2`,
        description: `Advanced concepts in ${category.title}.`,
        imageUrl: `https://jaro-website.s3.ap-south-1.amazonaws.com/2024/05/Performance-Marketing-for-Growth.jpg`,
        courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
        inviteUrl: "https://www.zoom.us/signin",
        startDate: "2025-07-10T15:00:00.000+00:00",
        endDate: "2025-08-10T15:00:00.000+00:00",
        duration: Math.floor(Math.random() * 31) + 1,
        category: category.title,
        enrolled: 0,
    },
    {
        status: 1,
        title: `${category.title} Course`,
        description: `Advanced concepts in ${category.title}.`,
        imageUrl: `https://jaro-website.s3.ap-south-1.amazonaws.com/2024/11/Banner.jpg`,
        courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
        inviteUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
        startDate: "2025-07-10T15:00:00.000+00:00",
        endDate: "2025-08-10T15:00:00.000+00:00",
        duration: Math.floor(Math.random() * 31) + 1,
        category: category.title,
        enrolled: 0,
    },
]);

const Jobs = Object.values(Companies).flatMap((company) =>
    Categories.flatMap((category) => [
        {
            status: 0,
            category: category.title,
            title: `Junior ${category.title} Specialist`,
            description: `# Junior ${category.title} Specialist\n\n**Company:** ${company.data.name}\n**Location:** At Office/Remote\n\nWe are looking for a Junior ${category.title} Specialist to join our team.`,
            company: company.data.name,
            isRemote: true,
            minSalary: Math.ceil(Math.random() * 30000 + 1),
            maxSalary: Math.ceil(Math.random() * 50000 + 1),
            minExperience: 1,
            location: { ...company.address },
            type: Math.floor(Math.random() * 4),
        },
        {
            status: 0,
            category: category.title,
            title: `Senior ${category.title} Specialist`,
            description: `# Senior ${category.title} Specialist\n\n**Company:** ${company.data.name}\n**Location:** At Office/Remote\n\nWe are looking for a Senior ${category.title} Specialist to join our team.`,
            company: company.data.name,
            isRemote: false,
            minSalary: Math.ceil(Math.random() * 60000 + 1),
            maxSalary: Math.ceil(Math.random() * 90000 + 1),
            minExperience: 5,
            location: { ...company.address },
            type: Math.floor(Math.random() * 4),
        },
    ])
);

const getMessages = (user1, user2) => [
    {
        sender: user1._id,
        receiver: user2._id,
        text: "Hey, how are you?",
        imageUrl: "",
    },
    {
        sender: user2._id,
        receiver: user1._id,
        text: "I'm good, thanks! How about you?",
        imageUrl: "",
    },
    {
        sender: user1._id,
        receiver: user2._id,
        text: "I'm doing well. Have you seen the latest project update?",
        imageUrl: "",
    },
    {
        sender: user2._id,
        receiver: user1._id,
        text: "Yes, I did. It looks promising.",
        imageUrl: "",
    },
    {
        sender: user1._id,
        receiver: user2._id,
        text: "Great! Here's a screenshot of the new design.",
        imageUrl: "https://dummyimage.com/400x400/DC3545",
    },
    {
        sender: user2._id,
        receiver: user1._id,
        text: "Wow, that looks amazing!",
        imageUrl: "",
    },
    {
        sender: user1._id,
        receiver: user2._id,
        text: "Thanks! We put a lot of effort into it.",
        imageUrl: "",
    },
    {
        sender: user2._id,
        receiver: user1._id,
        text: "I can see that. When is the next meeting?",
        imageUrl: "",
    },
    {
        sender: user1._id,
        receiver: user2._id,
        text: "It's scheduled for tomorrow at 10 AM.",
        imageUrl: "",
    },
    {
        sender: user2._id,
        receiver: user1._id,
        text: "Got it. I'll be there.",
        imageUrl: "",
    },
    {
        sender: user1._id,
        receiver: user2._id,
        text: "Perfect. See you then!",
        imageUrl: "",
    },
    {
        sender: user2._id,
        receiver: user1._id,
        text: "See you!",
        imageUrl: "",
    },
    {
        sender: user1._id,
        receiver: user2._id,
        text: "By the way, did you check the new feature?",
        imageUrl: "",
    },
    {
        sender: user2._id,
        receiver: user1._id,
        text: "Not yet. Can you send me a screenshot?",
        imageUrl: "",
    },
    {
        sender: user1._id,
        receiver: user2._id,
        text: "Sure, here it is.",
        imageUrl: "https://dummyimage.com/400x400/007BFF",
    },
    {
        sender: user2._id,
        receiver: user1._id,
        text: "Thanks! I'll check it out.",
        imageUrl: "",
    },
    {
        sender: user1._id,
        receiver: user2._id,
        text: "No problem. Let me know if you have any questions.",
        imageUrl: "",
    },
    {
        sender: user2._id,
        receiver: user1._id,
        text: "Will do. Thanks!",
        imageUrl: "",
    },
    {
        sender: user1._id,
        receiver: user2._id,
        text: "You're welcome.",
        imageUrl: "",
    },
    {
        sender: user2._id,
        receiver: user1._id,
        text: "Talk to you later.",
        imageUrl: "",
    },
];

const getNotifications = (user) => [
    { text: "Your profile has been updated successfully.", user: user.id },
    { text: "You have a new message.", user: user.id },
    { text: "Your course 'Software Development' starts tomorrow.", user: user.id },
    { text: "Reminder: Meeting scheduled at 10 AM tomorrow.", user: user.id },
    { text: "Your application for 'Junior Developer' has been received.", user: user.id },
    { text: "New job posting: 'Senior Developer' at Blue Flurry.", user: user.id },
    { text: "Your password has been changed successfully.", user: user.id },
    { text: "You have a new connection request from Muskaan.", user: user.id },
    { text: "Your resume has been viewed by Jaro Education.", user: user.id },
    { text: "New course available: 'Data Science'.", user: user.id },
    { text: "Your interview is scheduled for next Monday.", user: user.id },
    { text: "You have a new message from Admin.", user: user.id },
    { text: "Your subscription has been renewed.", user: user.id },
    { text: "New event: 'Tech Conference 2025' next week.", user: user.id },
    { text: "Your profile is 90% complete. Add more details.", user: user.id },
    { text: "You have a new endorsement from", user: user.id },
    { text: "Your course 'Machine Learning' has been completed.", user: user.id },
    { text: "New article: 'Top 10 Programming Languages in 2025'.", user: user.id },
    { text: "Your feedback is requested for the recent course.", user: user.id },
    { text: "You have a new notification from Blue Flurry.", user: user.id },
];

const getReferrals = (userId, userData) => [
    {
        user: userId,
        data: userData,
        status: 0,
        friendName: "Siddhant Jain",
        friendPhone: "9711469568",
        courseDetails: {
            courseName: "Software Development",
            courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
            courseId: 112923,
        },
    },
    {
        user: userId,
        data: userData,
        status: 1,
        friendName: "Rahul Kumar",
        friendPhone: "9876543210",
        courseDetails: {
            courseName: "Data Science",
            courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
            courseId: 112924,
        },
        payment: 2500,
    },
    {
        user: userId,
        data: userData,
        status: 2,
        friendName: "Priya Singh",
        friendPhone: "9812345670",
        courseDetails: {
            courseName: "Machine Learning",
            courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
            courseId: 112925,
        },
    },
    {
        user: userId,
        data: userData,
        status: 0,
        friendName: "Amit Sharma",
        friendPhone: "9898989898",
        courseDetails: {
            courseName: "Web Development",
            courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
            courseId: 112926,
        },
    },
    {
        user: userId,
        data: userData,
        status: 1,
        friendName: "Neha Gupta",
        friendPhone: "9767676767",
        courseDetails: {
            courseName: "Digital Marketing",
            courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
            courseId: 112927,
        },
        payment: 3500,
    },
    {
        user: userId,
        data: userData,
        status: 2,
        friendName: "Vikram Patel",
        friendPhone: "9945454545",
        courseDetails: {
            courseName: "Cloud Computing",
            courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
            courseId: 112928,
        },
    },
    {
        user: userId,
        data: userData,
        status: 0,
        friendName: "Anjali Verma",
        friendPhone: "9834343434",
        courseDetails: {
            courseName: "Artificial Intelligence",
            courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
            courseId: 112929,
        },
    },
    {
        user: userId,
        data: userData,
        status: 1,
        friendName: "Rajesh Mishra",
        friendPhone: "9723232323",
        courseDetails: {
            courseName: "Cyber Security",
            courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
            courseId: 112930,
        },
        payment: 4200,
    },
    {
        user: userId,
        data: userData,
        status: 2,
        friendName: "Meera Shah",
        friendPhone: "9612121212",
        courseDetails: {
            courseName: "DevOps",
            courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
            courseId: 112931,
        },
    },
    {
        user: userId,
        data: userData,
        status: 0,
        friendName: "Karan Malhotra",
        friendPhone: "9545454545",
        courseDetails: {
            courseName: "Blockchain",
            courseUrl: "https://www.youtube.com/watch?v=aGErHYbzdZQ",
            courseId: 112932,
        },
    },
];

module.exports = { Users, Companies, Upsells, Universities, HomeCarousels, Categories, Courses, Jobs, getMessages, getNotifications, getReferrals };
