const validator = require("validator");
const contentConfig = require("../features/content/content.config");
const { Field } = require("../utils/schemas");

module.exports = {
    $schemaName: "Content",
    $apiSlug: "content",
    type: new Field({
        name: "Type",
        type: Number,
        required: false,
        default: contentConfig.contentTypes.upsell,
        enum: Object.values(contentConfig.contentTypes),
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    title: new Field({
        name: "Title",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isLength(value, { min: 2 }),
        errorMessage: "Should be atleast 2 characters long",
        showInTable: false,
        showInForm: true,
        fullwidth: true,
        isSearchable: true,
    }),
    description: new Field({
        name: "Description",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    imageUrl: new Field({
        name: "Image URL",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isURL(value),
        errorMessage: "Image URL should be a valid url",
        showInTable: false,
        showInForm: true,
        fullWidth: true,
    }),
    link: new Field({
        name: "Link",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => !value || validator.isURL(value),
        errorMessage: "Link should be a valid url",
        showInTable: false,
        showInForm: true,
        fullWidth: true,
    }),
};
