const validator = require("validator");
const { Field } = require("../utils/schemas");
const { courseStatus } = require("../features/courses/courses.config");
const Content = require("./content.schema");

module.exports = {
    $schemaName: "Courses",
    $apiSlug: "courses",
    status: new Field({
        name: "Status",
        type: Number,
        required: false,
        default: courseStatus.webinar,
        enum: Object.values(courseStatus),
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    title: new Field({
        name: "Title",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isLength(value, { min: 2 }),
        errorMessage: "Should be atleast 2 characters long",
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    description: new Field({
        name: "Description",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    imageUrl: new Field({
        name: "Image URL",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isURL(value),
        errorMessage: "Image URL should be a valid url",
        showInTable: false,
        showInForm: true,
        fullWidth: true,
    }),
    previewUrl: new Field({
        name: "Preview URL",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isURL(value),
        errorMessage: "Image URL should be a valid url",
        showInTable: false,
        showInForm: true,
        fullWidth: true,
    }),
    courseUrl: new Field({
        name: "Course URL",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isURL(value),
        errorMessage: "Course URL should be a valid url",
        showInTable: false,
        showInForm: true,
        fullWidth: true,
    }),
    inviteUrl: new Field({
        name: "Invite URL",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isURL(value),
        errorMessage: "Invite URL should be a valid url",
        showInTable: false,
        showInForm: true,
        fullWidth: true,
    }),
    startDate: new Field({
        name: "Start Date",
        type: Date,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isDate(value),
        errorMessage: "Should be a valid date",
        showInTable: false,
        showInForm: true,
        fullwidth: false,
    }),
    endDate: new Field({
        name: "End Date",
        type: Date,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isDate(value),
        errorMessage: "Should be a valid date",
        showInTable: false,
        showInForm: true,
        fullwidth: false,
    }),
    duration: new Field({
        name: "Duration",
        type: Number,
        required: false,
        default: null,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    enrolled: new Field({
        name: "Students Enrolled",
        type: Number,
        required: false,
        default: 0,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: false,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    category: new Field({
        name: "Category",
        type: Content,
        required: false,
        default: null,
        enum: null,
        showInTable: true,
        showInForm: true,
        fullwidth: false,
    }),
};
