const validator = require("validator");
const Workspace = require("./workspace.schema");
const { Field } = require("../utils/schemas");

module.exports = {
    $schemaName: "Cron",
    $apiSlug: "cron",
    title: new Field({
        name: "Title",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isLength(value, { min: 2 }),
        errorMessage: "Should be atleast 2 characters long",
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    text: new Field({
        name: "Text",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isLength(value, { min: 2 }),
        errorMessage: "Should be atleast 2 characters long",
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    date: new Field({
        name: "Date",
        type: Date,
        required: false,
        unique: false,
        default: null,
        enum: null,
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    repeat: new Field({
        name: "Repeat?",
        type: Boolean,
        required: false,
        unique: false,
        default: false,
        enum: null,
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    frequency: new Field({
        name: "Frequency",
        type: Number,
        required: false,
        unique: false,
        default: 0,
        enum: null,
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    link: new Field({
        name: "Link",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    createdBy: new Field({
        name: "Workspace",
        type: Workspace,
        required: false,
        default: null,
        enum: null,
        showInTable: true,
        showInForm: true,
        fullwidth: false,
    }),
    completed: new Field({
        name: "Completed",
        type: Boolean,
        required: false,
        default: false,
        enum: null,
        showInTable: true,
        showInForm: false,
        fullwidth: false,
    }),
};
