const validator = require("validator");
const { Field } = require("../utils/schemas");
const { courseStatus } = require("../features/courses/courses.config");
const Content = require("./content.schema");

module.exports = {
    $schemaName: "JaroEducationCourses",
    $apiSlug: "jaro-education-courses",
    title: new Field({
        name: "Title",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isLength(value, { min: 2 }),
        errorMessage: "Should be atleast 2 characters long",
        showInTable: true,
        showInForm: true,
        fullwidth: true,
        isSearchable: true,
    }),
    courseUrl: new Field({
        name: "Course URL",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isURL(value),
        errorMessage: "Course URL should be a valid url",
        showInTable: false,
        showInForm: true,
        fullWidth: true,
    }),
    specialization: new Field({
        name: "Specialization",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        isSearchable: true,
    }),
    institute: new Field({
        name: "Institute",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        isSearchable: true,
    }),
};
