const validator = require("validator");
const { Field } = require("../utils/schemas");
const { jobStatus, jobTypes } = require("../features/jobs/jobs.config");
const Content = require("./content.schema");
const Workspace = require("./workspace.schema");
const countries = require("../constants/countries");
const { formatCurrency } = require("../utils/numbers.utils");

module.exports = {
    $schemaName: "Jobs",
    $apiSlug: "jobs",
    status: new Field({
        name: "Status",
        type: Number,
        required: false,
        default: jobStatus.active,
        enum: Object.values(jobStatus),
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    type: new Field({
        name: "Job Type",
        type: Number,
        required: false,
        default: jobTypes.fullTime,
        enum: Object.values(jobTypes),
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    category: new Field({
        name: "Category",
        type: Content,
        required: false,
        default: null,
        enum: null,
        showInTable: true,
        showInForm: true,
        fullwidth: false,
    }),
    title: new Field({
        name: "Title",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isLength(value, { min: 2 }),
        errorMessage: "Should be atleast 2 characters long",
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    description: new Field({
        name: "Description",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    company: new Field({
        name: "Company",
        type: Workspace,
        required: false,
        default: null,
        enum: null,
        showInTable: true,
        showInForm: true,
        fullwidth: false,
    }),
    isRemote: new Field({
        name: "Is Remote?",
        type: Boolean,
        required: false,
        default: false,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
    }),
    minSalary: new Field({
        name: "Min. Salary",
        type: Number,
        required: false,
        default: 0,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    maxSalary: new Field({
        name: "Max. Salary",
        type: Number,
        required: false,
        default: 0,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    salaryRange: new Field({
        name: "Salary Range",
        type: String,
        required: false,
        default: null,
        enum: null,
    }),
    minExperience: new Field({
        name: "Min. Experience",
        type: Number,
        required: false,
        default: 0,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    maxExperience: new Field({
        name: "Max. Experience",
        type: Number,
        required: false,
        default: 0,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    location: {
        street: new Field({
            name: "Street Address",
            type: String,
            required: false,
            unique: false,
            default: null,
            enum: null,
            validator: (value) => !value || (value && value.length > 0),
            errorMessage: "Street address is required",
            showInTable: true,
            showInForm: true,
            fullWidth: true,
            sortAsc: (a, b) => a.localeCompare(b),
            sortDesc: (a, b) => b.localeCompare(a),
            filter: (address, check) => address.toLowerCase().includes(check.toLowerCase()),
        }),
        city: new Field({
            name: "City",
            type: String,
            required: false,
            unique: false,
            default: null,
            enum: null,
            validator: (value) => !value || (value && value.length > 0),
            errorMessage: "City is required",
            showInTable: true,
            showInForm: true,
            fullWidth: false,
            sortAsc: (a, b) => a.localeCompare(b),
            sortDesc: (a, b) => b.localeCompare(a),
            filter: (address, check) => address.toLowerCase().includes(check.toLowerCase()),
        }),
        state: new Field({
            name: "State",
            type: String,
            required: false,
            unique: false,
            default: null,
            enum: null,
            validator: (value) => !value || (value && value.length > 0),
            errorMessage: "State is required",
            showInTable: true,
            showInForm: true,
            fullWidth: false,
            sortAsc: (a, b) => a.localeCompare(b),
            sortDesc: (a, b) => b.localeCompare(a),
            filter: (address, check) => address.toLowerCase().includes(check.toLowerCase()),
        }),
        pincode: new Field({
            name: "Pincode",
            type: String,
            required: false,
            unique: false,
            default: null,
            enum: null,
            validator: (value) => !value || validator.isPostalCode(value, "IN"),
            errorMessage: "Should be a valid pincode",
            showInTable: true,
            showInForm: true,
            fullWidth: false,
            sortAsc: (a, b) => a.localeCompare(b),
            sortDesc: (a, b) => b.localeCompare(a),
            filter: (code, check) => code.includes(check),
        }),
        country: new Field({
            name: "Country",
            type: String,
            required: false,
            unique: false,
            default: null,
            enum: Object.values(countries), // Example country options
            validator: (value) => !value || Object.values(countries).includes(value),
            errorMessage: "Should be a valid country",
            showInTable: true,
            showInForm: true,
            fullWidth: false,
            sortAsc: (a, b) => a.localeCompare(b),
            sortDesc: (a, b) => b.localeCompare(a),
            filter: (country, check) => country.toLowerCase().includes(check.toLowerCase()),
        }),
        lat: new Field({
            name: "Latitude",
            type: Number,
            required: false,
            unique: false,
            default: null,
            enum: null,
            validator: (value) => value !== null && !isNaN(value) && value >= -90 && value <= 90,
            errorMessage: "Latitude should be a number between -90 and 90",
            showInTable: true,
            showInForm: true,
            fullWidth: false,
            sortAsc: (a, b) => a - b,
            sortDesc: (a, b) => b - a,
            filter: (lat, check) => lat.toString().includes(check.toString()),
        }),
        long: new Field({
            name: "Longitude",
            type: Number,
            required: false,
            unique: false,
            default: null,
            enum: null,
            validator: (value) => value !== null && !isNaN(value) && value >= -180 && value <= 180,
            errorMessage: "Longitude should be a number between -180 and 180",
            showInTable: true,
            showInForm: true,
            fullWidth: false,
            sortAsc: (a, b) => a - b,
            sortDesc: (a, b) => b - a,
            filter: (long, check) => long.toString().includes(check.toString()),
        }),
    },
    pre: {
        find: function (next) {
            this.populate("company");
            return next();
        },
        findOne: function (next) {
            this.populate("company");
            return next();
        },
        findOneAndUpdate: function (next) {
            this.populate("company");
            return next();
        },
        findMany: function (next) {
            this.populate("company");
            return next();
        },
    },
    post: {
        find: function (docs) {
            docs.forEach((doc, index) => {
                let obj = doc.toObject();
                // obj.salaryRange = `${formatCurrency(obj.minSalary)} - ${formatCurrency(obj.maxSalary)}`;
                docs[index] = obj;
            });
        },
        findOne: function (obj) {
            // obj.salaryRange = `${formatCurrency(obj.minSalary)} - ${formatCurrency(obj.maxSalary)}`;
        },
        findOneAndUpdate: function (obj) {
            // obj.salaryRange = `${formatCurrency(obj.minSalary)} - ${formatCurrency(obj.maxSalary)}`;
        },
        findMany: function (docs) {
            docs.forEach((doc, index) => {
                let obj = doc.toObject();
                // obj.salaryRange = `${formatCurrency(obj.minSalary)} - ${formatCurrency(obj.maxSalary)}`;
                docs[index] = obj;
            });
        },
    },
};
