const { Field } = require("../utils/schemas");
const validator = require("validator");
const referralConfig = require("../features/referral/referral.config");
const Workspace = require("./workspace.schema");

module.exports = {
    $schemaName: "Referral",
    $apiSlug: "referral",
    user: new Field({
        name: "User",
        type: Workspace,
        required: false,
        default: null,
        enum: null,
        showInTable: true,
        showInForm: true,
        fullwidth: false,
    }),
    data: new Field({
        name: "User's Data",
        type: Object,
        required: false,
        default: null,
        enum: null,
        showInTable: true,
        showInForm: true,
        fullwidth: false,
    }),
    status: new Field({
        name: "Status",
        type: Number,
        required: false,
        default: referralConfig.status.active,
        enum: Object.values(referralConfig.status),
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: false,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (status, check) => +status === +check,
    }),
    payment: new Field({
        name: "Payment",
        type: Number,
        required: false,
        default: 0,
        showInTable: true,
        showInForm: false,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (status, check) => +status === +check,
    }),
    friendName: new Field({
        name: "Friend's Name",
        type: String,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isLength(value, { min: 1 }),
        errorMessage: "Should be atleast 5 character long",
        showInTable: false,
        showInForm: true,
        fullwidth: true,
    }),
    friendPhone: new Field({
        name: "Friend's Phone",
        type: String,
        required: false,
        default: null,
        enum: null,
        validator: (value) => validator.isMobilePhone(value, "en-IN"),
        errorMessage: "Should be a valid phone number",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a.replace(/\D/g, "").localeCompare(b.replace(/\D/g, "")),
        sortDesc: (a, b) => b.replace(/\D/g, "").localeCompare(a.replace(/\D/g, "")),
        filter: (number, check) => number.replace(/\D/g, "").includes(check.replace(/\D/g, "")),
    }),
    courseDetails: new Field({
        name: "Course Details",
        type: Object,
        required: false,
        default: null,
        enum: null,
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: false,
        fullwidth: false,
    }),
};
