const validator = require("validator");
const moment = require("moment");

const { Field } = require("../utils/schemas");

module.exports = {
    $schemaName: "User",
    $apiSlug: "auth",
    name: {
        first: new Field({
            name: "First Name",
            type: String,
            required: false,
            unique: false,
            default: null,
            enum: null,
            validator: (value) => validator.isLength(value, { min: 3 }),
            errorMessage: "Should be atleast 3 characters long",
            showInTable: false,
            showInForm: true,
            fullwidth: false,
        }),
        middle: new Field({
            name: "Middle Name",
            type: String,
            required: false,
            unique: false,
            default: null,
            enum: null,
            validator: null,
            errorMessage: "",
            showInTable: false,
            showInForm: true,
            fullwidth: false,
        }),
        last: new Field({
            name: "Last Name",
            type: String,
            required: false,
            unique: false,
            default: null,
            enum: null,
            validator: null,
            errorMessage: "",
            showInTable: false,
            showInForm: true,
            fullwidth: false,
        }),
    },
    email: new Field({
        name: "Email",
        type: String,
        required: false,
        unique: true,
        default: null,
        enum: null,
        validator: (value) => validator.isEmail(value),
        errorMessage: "Should be a valid email",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a.localeCompare(b),
        sortDesc: (a, b) => b.localeCompare(a),
        filter: (email, check) => email.toLowerCase().includes(check.toLowerCase()),
    }),
    phone1: new Field({
        name: "Primary Phone",
        type: String,
        required: false,
        unique: true,
        default: null,
        enum: null,
        validator: (value) => validator.isMobilePhone(value, "en-IN"),
        errorMessage: "Should be a valid phone number",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a.replace(/\D/g, "").localeCompare(b.replace(/\D/g, "")),
        sortDesc: (a, b) => b.replace(/\D/g, "").localeCompare(a.replace(/\D/g, "")),
        filter: (number, check) => number.replace(/\D/g, "").includes(check.replace(/\D/g, "")),
    }),
    phone2: new Field({
        name: "Secondary Phone",
        type: String,
        required: false,
        default: null,
        enum: null,
        validator: (value) => validator.isMobilePhone(value, "en-IN"),
        errorMessage: "Should be a valid phone number",
        showInTable: false,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a.replace(/\D/g, "").localeCompare(b.replace(/\D/g, "")),
        sortDesc: (a, b) => b.replace(/\D/g, "").localeCompare(a.replace(/\D/g, "")),
        filter: (number, check) => number.replace(/\D/g, "").includes(check.replace(/\D/g, "")),
    }),
    dob: new Field({
        name: "Date of Birth",
        type: Date,
        required: false,
        unique: false,
        default: null,
        enum: null,
        validator: (value) => validator.isDate(value),
        errorMessage: "Should be a valid date",
        showInTable: false,
        showInForm: true,
        fullwidth: false,
    }),
    fullName: new Field({
        name: "Name",
        type: String,
        getter: function () {
            let value = this.name.first;
            if (this.name.middle) value += " " + this.name.middle;
            if (this.name.last) value += " " + this.name.last;
            return value;
        },
        showInTable: true,
        sortAsc: (a, b) => a.localeCompare(b),
        sortDesc: (a, b) => b.localeCompare(a),
        filter: (name, check) => name.toLowerCase().includes(check.toLowerCase()),
    }),
    age: new Field({
        name: "Age",
        type: Number,
        getter: function () {
            return moment().diff(moment(this.dob), "years");
        },
        showInTable: true,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (age, check) => +age === +check,
    }),
};
